CREATE TABLE `NUMBER8` (
	`id` INT NOT NULL AUTE_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100),
	`element` TEXT[]
);

INSERT INTO NUMBER8 VALUES ('31 올스타', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('31 요거트', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('NEW 슈팅스타', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('NEW 이상한 나라의 솜사탕', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('NEW 자모카 아이스 훠지', array['우유', '호두']);
INSERT INTO NUMBER8 VALUES ('고라파덕 아이스크림 콘', array[]);
INSERT INTO NUMBER8 VALUES ('그린티', array['우유']);
INSERT INTO NUMBER8 VALUES ('나와라 꼬부기', array['우유']);
INSERT INTO NUMBER8 VALUES ('뉴욕 치즈케이크', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('딸기 말랑 블라스트', array['우유']);
INSERT INTO NUMBER8 VALUES ('딸기 연유 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('레몬라임 블라스트', array[]);
INSERT INTO NUMBER8 VALUES ('레인보우 샤베트', array['우유']);
INSERT INTO NUMBER8 VALUES ('맥심 모카골드 블라스트', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('민트 초코 모카', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('민트 초콜릿 칩', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('밀크 쉐이크', array['우유']);
INSERT INTO NUMBER8 VALUES ('바닐라', array['우유']);
INSERT INTO NUMBER8 VALUES ('바닐라빈 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('바람과 함께 사라지다', array['우유', '대두', '밀', '계란']);
INSERT INTO NUMBER8 VALUES ('베리베리 스트로베리', array['우유']);
INSERT INTO NUMBER8 VALUES ('복숭아 아이스티', array['복숭아']);
INSERT INTO NUMBER8 VALUES ('브라운 버터 메이플', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('블랙 소르베', array['오징어']);
INSERT INTO NUMBER8 VALUES ('사랑에 빠진 외계인', array['우유', '계란', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('설향 딸기 블라스트', array[]);
INSERT INTO NUMBER8 VALUES ('스위스미스 아이스 초코', array['우유']);
INSERT INTO NUMBER8 VALUES ('스위스미스 핫초코', array['우유']);
INSERT INTO NUMBER8 VALUES ('쌀떡궁합', array['우유', '밀', '대두']);
INSERT INTO NUMBER8 VALUES ('아메리카노', array[]);
INSERT INTO NUMBER8 VALUES ('아메리카노(L)', array[]);
INSERT INTO NUMBER8 VALUES ('아몬드 봉봉', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('아몬드 봉봉 블라스트', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('아빠는 딸바봉', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('아이스 민트초코 모카', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('아이스 바닐라빈 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('아이스 아메리카노', array[]);
INSERT INTO NUMBER8 VALUES ('아이스 아메리카노 (L)', array[]);
INSERT INTO NUMBER8 VALUES ('아이스 연유 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('아이스 유자 캐모마일 티', array[]);
INSERT INTO NUMBER8 VALUES ('아이스 카라멜 마끼아또', array['우유']);
INSERT INTO NUMBER8 VALUES ('아이스 카페 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('아이스 흑임자 라떼', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('애플 민트', array['우유']);
INSERT INTO NUMBER8 VALUES ('엄마는 외계인', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('엄마는 외계인 블라스트', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('연유 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('오레오 딸기 쉐이크', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 민트초코 쉐이크', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 쉐이크', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 초코 쉐이크', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 카푸치노 블라스트', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 쿠키 앤 민트', array['우유', '대두', '밀', '호두']);
INSERT INTO NUMBER8 VALUES ('오레오 쿠키 앤 크림', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('오레오 쿠키 앤 크림치즈', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('윌넛', array['우유', '호두']);
INSERT INTO NUMBER8 VALUES ('유자 캐모마일 티', array['없음']);
INSERT INTO NUMBER8 VALUES ('자모카 아몬드 오가닉 레디팩', array['우유']);
INSERT INTO NUMBER8 VALUES ('쫀떡궁합', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('찰떡콩떡', array['우유', '대두', '밀', '땅콩']);
INSERT INTO NUMBER8 VALUES ('체리츄빌레', array['우유']);
INSERT INTO NUMBER8 VALUES ('초코 쿠키 쥬빌레 레디팩', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('초코나무 숲', array['우유', '대두', '밀']);
INSERT INTO NUMBER8 VALUES ('초콜릿 무스', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('카라멜 마끼아또', array['우유']);
INSERT INTO NUMBER8 VALUES ('카페 라떼', array['우유']);
INSERT INTO NUMBER8 VALUES ('카푸치노 블라스트 리얼샷', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('카푸치노 블라스트 모카', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('콜드브루 아메리카노', array[]);
INSERT INTO NUMBER8 VALUES ('콜드브루 오트라떼', array[]);
INSERT INTO NUMBER8 VALUES ('쿨쿨 잠맘보 밀키소다 블라스트', array['우유']);
INSERT INTO NUMBER8 VALUES ('푸린 아이스크림 콘', array[]);
INSERT INTO NUMBER8 VALUES ('피스타치오 아몬드', array['우유']);
INSERT INTO NUMBER8 VALUES ('피카츄 초코바나나 블라스트', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('피카피카 피카츄', array['우유', '대두']);
INSERT INTO NUMBER8 VALUES ('흑임자 라떼', array['우유', '대두']);
