CREATE TABLE `NUMBER6` (
	`id` INT NOT NULL AUTE_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100),
	`element` TEXT[]
);

INSERT INTO NUMBER5 VALUES ('아라비아따 리코타 치킨 버거', array['달걀', '우유', '대두', '밀', '돼지고기', '토마토', '닭고기']);
INSERT INTO NUMBER5 VALUES ('트리플 치즈버거', array['우유', '대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('더블 불고기 버거', array['달걀', '우유', '대두', '밀', '되지고기', '조개류', '굴']);
INSERT INTO NUMBER5 VALUES ('빅맥', array['달걀', '우유', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('맥스파이시 상하이 버거', array['달걀', '대두', '밀', '토마토', '닭고기']);
INSERT INTO NUMBER5 VALUES ('1955 버거', array['달걀', '우유', '대두', '밀', '돼지고기', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('맥치킨 모짜렐라', array['달걀', '우유', '대두', '밀', '토마토', '닭고기']);
INSERT INTO NUMBER5 VALUES ('더블 필레 오 피쉬', array['달걀, '우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('필레 오 피쉬', array['달걀', '우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('맥치킨', array['달걀', ''대두', '밀', '닭고기']);
INSERT INTO NUMBER5 VALUES ('에그 불고기 버거', array['달걀', '대두', '밀', '돼지고기', '조개류', '굴']);
INSERT INTO NUMBER5 VALUES ('불고기 버거', array['달걀', '우유', '대두', '돼지고기', '조개류', '굴']);
INSERT INTO NUMBER5 VALUES ('슈슈 버거', array['달걀', '우유', '대두', '밀', '토마토', '새우', '쇠고기', '굴']);
INSERT INTO NUMBER5 VALUES ('슈비 버거', array['달걀', '우유', '대두', '밀', '토마토', '새우', '쇠고기', '굴']);
INSERT INTO NUMBER5 VALUES ('베이컨 토마토 치즈', array['달걀', '우유', '대두', '밀', '돼지고기', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('더블 쿼터파운더 치즈', array['우유', '대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('쿼터파운더 치즈', array['우유', '대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('치즈버거', array['우유', '대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('더블 치즈버거', array['우유', '대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('햄버거', array['대두', '밀', '토마토', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('스파이시 맥너겟', array['대두', '밀', '토마토', '닭고기']);
INSERT INTO NUMBER5 VALUES ('소시지 스낵랩', array['달걀', '대두', '밀', '돼지고기', '쇠고기']);
INSERT INTO NUMBER5 VALUES ('상하이 치킨 스낵랩', array['달걀', '대두', '밀', '돼지고기', '닭고기']);
INSERT INTO NUMBER5 VALUES ('애플 파이', array['밀']);
INSERT INTO NUMBER5 VALUES ('골든 모짜렐라 치즈 스틱', array['우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('맥너겟', array['대두', '밀', '닭고기']);
INSERT INTO NUMBER5 VALUES ('맥스파이시 치킨 텐더', array['대두', '밀', '닭고기']);
INSERT INTO NUMBER5 VALUES ('후렌치 후라이', array['대두']);
INSERT INTO NUMBER5 VALUES ('스트링 치즈' array['우유']);
INSERT INTO NUMBER5 VALUES ('오렌지 칠리 소스' array['토마토']);
INSERT INTO NUMBER5 VALUES ('스위트 앤 사워 소스' array['대두', '밀', '아황산류', '굴']);
INSERT INTO NUMBER5 VALUES ('스위트 앤 칠리 소스' array['토마토']);
INSERT INTO NUMBER5 VALUES ('케이준 소스' array['계란', '대두']);
INSERT INTO NUMBER5 VALUES ('딸기 칠러' array[]);
INSERT INTO NUMBER5 VALUES ('자두 칠러' array[]);
INSERT INTO NUMBER5 VALUES ('바닐라 라떼' array['우유']);
INSERT INTO NUMBER5 VALUES ('카페라떼' array['우유']);
INSERT INTO NUMBER5 VALUES ('카푸치노' array['우유']);
INSERT INTO NUMBER5 VALUES ('아메리카노' array[]);
INSERT INTO NUMBER5 VALUES ('에스프레소' array[]);
INSERT INTO NUMBER5 VALUES ('드립 커피' array[]);
INSERT INTO NUMBER5 VALUES ('아이스 바닐라 라떼' array['우유']);
INSERT INTO NUMBER5 VALUES ('아이스 카페라떼 (시럽 없음)' array['우유']);
INSERT INTO NUMBER5 VALUES ('아이스 아메리카노 (시럽 없음)' array[]);
INSERT INTO NUMBER5 VALUES ('아이스 드립 커피 (시럽 없음)' array[]);
INSERT INTO NUMBER5 VALUES ('코카-콜라' array[]);
INSERT INTO NUMBER5 VALUES ('코카-콜라 제로' array[]);
INSERT INTO NUMBER5 VALUES ('스프라이트' array[]);
INSERT INTO NUMBER5 VALUES ('환타' array[]);
INSERT INTO NUMBER5 VALUES ('디카페인 카페라떼' array['우유']);
INSERT INTO NUMBER5 VALUES ('디카페인 카푸치노' array['우유']);
INSERT INTO NUMBER5 VALUES ('디카페인 아메리카노' array[]);
INSERT INTO NUMBER5 VALUES ('디카페인 에스프레소' array[]);
INSERT INTO NUMBER5 VALUES ('디카페인 아이스 카페라떼 (시럽 없음)' array['우유']);
INSERT INTO NUMBER5 VALUES ('디카페인 아이스 아메리카노 (시럽 없음)' array[]);
INSERT INTO NUMBER5 VALUES ('바닐라 쉐이크' array['우유']);
INSERT INTO NUMBER5 VALUES ('딸기 쉐이크' array['우유']);
INSERT INTO NUMBER5 VALUES ('초코 쉐이크' array['우유']);
INSERT INTO NUMBER5 VALUES ('우유' array['우유']);
INSERT INTO NUMBER5 VALUES ('생수' array[]);
INSERT INTO NUMBER5 VALUES ('허쉬 프레첼 맥플러리', array['우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('오레오 맥플러리', array['우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('베리 스트로베리 맥플러리', array['우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('초코 선데이 아이스크림', array['우유']);
INSERT INTO NUMBER5 VALUES ('딸기 선데이 아이스크림', array['우유']);
INSERT INTO NUMBER5 VALUES ('바닐라 선데이 아이스크림', array['우유']);
INSERT INTO NUMBER5 VALUES ('베이컨 토마토 에그 소프트 번', array['달걀', '대두', '밀', '돼지고기', '토마토']);
INSERT INTO NUMBER5 VALUES ('소시지 토마토 에그 소프트 번', array['달걀', '우유', '대두', '밀', '돼지고기', '토마토']);
INSERT INTO NUMBER5 VALUES ('소시지 토마토 에그 머핀', array['달걀', '대두', '밀', '돼지고기', '토마토']);
INSERT INTO NUMBER5 VALUES ('에그 맥머핀', array['달걀', '우유', '대두', '밀', '돼지고기']);
INSERT INTO NUMBER5 VALUES ('베이컨 에그 맥머핀', array['달걀', '우유', '대두', '밀', '돼지고기']);
INSERT INTO NUMBER5 VALUES ('소시지 에그 맥머핀', array['달걀', '우유', '대두', '밀', '돼지고기']);
INSERT INTO NUMBER5 VALUES ('치킨 치즈 머핀', array['달걀', '우유', '대두', '밀', '닭고기']);
INSERT INTO NUMBER5 VALUES ('디럭스 브렉퍼스트', array['달걀', '우유', '대두', '밀', '돼지고기']);
INSERT INTO NUMBER5 VALUES ('핫케익', array['달걀', '우유', '대두', '밀']);
INSERT INTO NUMBER5 VALUES ('딸기잼' array[]);
INSERT INTO NUMBER5 VALUES ('시럽', array['아황산류']);
INSERT INTO NUMBER5 VALUES ('버터', array['우유', '대두']);
